server:
  port: 8080
spring:
  jackson:
    parser:
      allow-unquoted-control-chars: true # 允许json格式数据中存在未转义的字符
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.72.52:3306/heyunetwork-demo?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: PASSWORDis1024
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: NNNnoteHikariPool
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:com/heyunetwork/demo/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl